spring.application.name=ChatApplication
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/TestDB2
spring.datasource.username=root
spring.datasource.password=secret
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Show formatted SQL output (optional but improves readability)
#spring.jpa.properties.hibernate.format_sql=true
# Show the actual values bound to SQL parameters
#logging.level.org.hibernate.type.descriptor.sql=TRACE

